library(ggplot2)
library(reshape2)
library(RColorBrewer)
library(grDevices)
library(binovisualfields)
library(fields)
rm(list=ls(all=TRUE))

#Population simulation parameters
Npop <- 100 #initial pop size (not important)
Tmax <- 300 #max years
Tfishing <- 100# when we start fishing
Trecovery<- 200 #when fishing ends
Ngroup <- 2 #Number of separate population groups - IE females,males
Amax <- c(8, 4) #Fischer and Thompson 2004

#Life history parameters for females and males:
initialsize = c(120, 120) #mm size at "recruitment" #females, males from Fischer and Thompson 2004
#Will need to determine sex specific Linf values from data collected this fall
Linf = c(556.5,332.5)  #mm, average max size at maturity for use in von Bert growth function (VBGF) from Fischer and Thompson 2004
#Collect sex specific data this fall
k = c(0.51, 1.03)   # VBGF growth coefficients from Fischer and Thompson 2004
#Collect sex specific data this fall
#Do not currently have parameters
c = c(0.00000347,0.00000347) #mass-at-size coeff (in g) #from Fischer and Thompson 2001
b = c(3.21,3.21)   #mass-at-size exp from Fischer and Thompson 2001

Pfemale <- c(0.5,0.45,0.4,0.35,0.3, .25, .2, .15, .1,.05)

#We will run the population projection model for varying levels of fishing pressure:
mu_f = c(0,0.1,0.2, 0.3, 0.4, 0.5, 0.6,0.7,0.8,0.9)

lRdiff <- length(Pfemale)

#assuming Beverton Holt recruitment, these are general parameters I adjust  by eye
alpha = 0.18
beta = 1e-18

matsize <- c(350, 250) #mm, Daniels 2000

natmort <- array(dim=c(Amax[1],Ngroup),data=c(c(1.341,0.585,0.441,0.386,0.359,0.344,0.336,0),c(1.341,0.664,0.565,0.537,0,0,0,0))) #calculated using Lorenzen age-length equation, based on lengths at age generated by the von bert function

pmat <- array(dim=c(Amax[1],Ngroup,lRdiff), data=0) #this will hold probability of maturation each year, note it is a matrix 
pmat[(Amax[2]+1):Amax[1], 2, lRdiff] <- 0 #age-dependent maturity

###Set up vectors to store age-specific life history characters and fishing probability
W <- array(dim=c(Amax[1],Ngroup, lRdiff), data=0) #this vector will hold individual weight-at-age
L <- array(dim=c(Amax[1],Ngroup, lRdiff), data=0) #length-at-age
mu <- array(dim=c(Amax[1],Ngroup, lRdiff), data=0) #mortality-at-age (this is constant in initial case)

select <- array(dim=c(Amax[1],Ngroup), data=0) #probability of being caught at each age, given size-at-age
Fishing <- array(dim=c(Amax[1],Ngroup), data=0) #Fishing mortality at age

N <- array(dim=c(Amax[1],Tmax,Ngroup,lRdiff), data=0)  #this matrix holds population numbers in each year class over time

E <- array(dim=c(1,Tmax,lRdiff), data=0)  #holds number of eggs at each time
P <- array(dim=c(1,Tmax,lRdiff), data=0)  #holds number of larvae at each time
Catch <- array(dim=c(Amax[1],Tmax,Ngroup, lRdiff), data=0)  #store Catch number or biomass, given selectivity
Yield <- array(dim=c(Amax[1],Tmax,Ngroup, lRdiff), data=0) #store yield biomass
Biomass <- array(dim=c(Amax[1],Tmax,Ngroup,lRdiff),data=0) #Biomass

TEP=matrix(0, nrow=length(mu_f), ncol=lRdiff)
SPR=matrix(0, nrow=length(mu_f), ncol=lRdiff)
TS_SPR=matrix(0, nrow=length(mu_f), ncol=lRdiff)
Total_Yield = matrix(0, nrow=length(mu_f), ncol=lRdiff)
Total_Catch = matrix(0, nrow=length(mu_f), ncol=lRdiff)
Sexratio = matrix(0, nrow=length(mu_f), ncol=lRdiff)

Nhat = matrix(0, nrow=length(mu_f), ncol=lRdiff)
Bhat = matrix(0, nrow=length(mu_f), ncol=lRdiff) 

#Age-dependent size, maturation, and mortality 
#we first need to set initial conditions and define the relationships between age, size, maturation, mortality, and fishery selectivity. 
#In this simple case, we are assuming asymptotic selectivity based on length, not mass.

for (R in 1:lRdiff ) {
  
  prop <- c(Pfemale[R], (1-Pfemale[R]))#we now define Prop inside the R loop 


for(g in 1:Ngroup) { #for both sexes, where g =1 is female and g = 2 is male
  
  N[1:5,1,g,R] = Npop*prop[g] #initial population size
  
  L[1,g,R] = initialsize[g] #initial size when entering the population model 
  
  #Next define age-specific growth, mortality, and selectivity functions 
  
  for (a in 1:((Amax[1])-1)) { #used to be Amax-1
    if (a <= Amax[g]) { #this if statement allows us to vary maximum age of each sex 
      
      #GROWTH 		 
      L[a+1,g,R]= Linf[g]*(1-exp(-k[g])) + (L[a,g,R])*exp(-k[g]) #length at age
      W[a+1,g,R]=  c[g]*L[a+1,g,R]^b[g] #weight at age
      
      
      
      #Maturation
      if (L[a,g,R] > matsize[g]) pmat[ a, g,R] = 1 else pmat[a,g,R] = 0
      
      
      #FISHERY SELECTIVITY
      # # MINIMUM SIZE: 
      if (L[a, 1,R] > 260.4 )  select[a,1] = 1/(1+exp(-0.02*(L[a,1,R]-300))) else select[a,1] = 0 #Minimum size at 26.04 cm
     
    } #endif
    
    
  }#end a loop
}#next group (sex)

matplot(select[,],type="l", lwd=5,las=1,ylab="Selectivity",xlab="Age", col=c('grey40','grey80'), lty=1)

matplot(L[,,R], type="l", lwd=5, las=1, ylab ="Length (mm)", xlab = "Age", col=c('grey40','grey80'), lty=1) 
matplot(pmat[,,R], type="l", lwd=5, las=1, ylab ="Probability Mature", xlab = "Age", col=c('grey40','grey80'), lty=1) 

#define female egg production as a function of her mass
eggs <- 2760632000*(c*W[,1,R]^b) #estimate of mass-specific egg production (in grams) from Watanabe and Carroll 2001   

#Eggs will be a vector, one egg value for each age

#################################################################################################################
#We will run the population projection model for varying levels of fishing pressure:

###Simulate population dynamics, start from an arbitrary population size and let the population reach a stable age distribution, then start fishing. The population will reach a new, fished, steady state (stable age dist).
## *Note: For the base case, recruitment is based only on Female abundance.

for (fish in 1:length(mu_f)) { #loop over all levels of fishing mortality
  for(t in 1:(Tmax-1)) {
    E[t]=sum(N[, t,1,R]*eggs[-9]*pmat[, 1,R]) #assuming spawning occurs between 1 t and the next and depends ONLY on mature females
    P[t]= E[t]  #assumes all eggs are fertilized
    
    for(g in 1:2) { #here g is sex, where g = 1 is female, and g = 2 is male  
      
      N[1,t+1,g,R]= (alpha*P[t]/(1 + beta*P[t]))*prop[g] #this is the N_0 class that is born and recruits to the population model in the next time step 
      #this calculates  the probability of fishing mortality, given selectivity function
      age <- 1
      for (age in 1:((Amax[g])-1)) {  
        
        if( t > Tfishing & t < Trecovery) { #If want to model recovery from fishing
       # if( Tfishing <t ) { #If don't want to model recovery from fishing
          
         Fishing[age,g] = select[age,g]*mu_f[fish]
         Fishing[Amax[g], g] = select[Amax[g], g]*mu_f[fish] 
          
        } else {
          Fishing[age,g] = 0
        } #end if
        
        
        Catch[,t+1,g,R] <- N[,t,g,R]*(1-exp(-Fishing[,g]))  #Note this is catch numbers, not biomass, assumes natural mortality occurs later in the year than fishing
        #Catch of all the ages, the number of individuals in every age class * fishing mortality of every age class (Fishing=instantaneus fishing mortality)
        Yield[,t+1,g,R] <- N[,t,g, R]*(1-exp(-Fishing[,g]))*W[,g,R] #biomass yield- think TAC
        #Calculate survival
        N[age+1,t+1,g,R] <- N[age,t,g,R]*exp(-natmort[age,g]-Fishing[age,g]) #surviving fish in each group enter the next age class in the following year, all fish get to spawn before mortality 		 
        print(N[6:7,t,1,1])
        Biomass[age,t,g,R]<-N[age,t,g,R]*W[age,g,R]
        
      } #end second age loop
    } #end sex g loop
  } #end t loop
  
  #SPR=spawning potential ratio
  TEP[fish, R] = E[Tfishing-1]/1
  SPR[fish,R] = E[Tfishing+50]/E[Tfishing-1]
  TS_SPR[fish,R] = E[Tfishing+50]/TEP[1,1]
  #All fish, all sexes
  Total_Yield[fish, R] = sum(Yield[,Tfishing+20, , R])
  Total_Catch[fish, R] = sum(Catch[,Tfishing+20, , R])
  
  #Matrix of age at time in steady state of females/males
  Sexratio[fish, R] = sum(N[, Tfishing+20, 1, R])/sum(N[-1, Tfishing+20, 2, R])
  
  Nhat[fish, R] =  sum(N[, Tfishing+20,  1, R]) #/ sum(N[, Tfishing-20,  , R])
  Bhat[fish, R] = sum(Biomass[, Tfishing+20,  1, R]) # / sum(Biomass[, Tfishing-20,  , R])
  
} #end fishing mortality loop

#just females
# plot(colSums(N[,,1, R]), type="l")
# 
# plot(colSums(Biomass[,,1, R]),type="l")

#total Abundance
plot(colSums(N[,,1, R])+colSums(N[,,2, R]),type="l")

#total Biomass 
plot(colSums(Biomass[,,1, R])+colSums(Biomass[,,2,R]),type="l")

#Plot age structures
age_structure <- N[, Tfishing-1, ,R ]

barplot(t(age_structure), beside=T)
x<- as.data.frame(age_structure)
names(x) <- c("females", "males")
#add age column
x$age<-c(1,2,3,4,5,6,7,8)
age<-c(1,2,3,4,5,6,7,8)
dat2 <- melt(x,id.vars="age")

ggplot(dat2) + aes(age) + coord_flip() +  theme_bw()   +
  xlab("Age")+
  ylab("Abundance")+
  geom_bar(data =  dat2[dat2[["variable"]]=="females",],
           aes(y = -value, fill="Females"), stat="identity", fill= "grey40")+ geom_bar(data =  dat2[dat2[["variable"]]=="males",], aes(y = value, fill="Males"), stat="identity", fill="grey80") +ylim(-10e+16,10e+16)

} #end R loop

#install.packages("fields")#quartz()
par(mfrow = c(1, 1))
image(1:10, 1:10, t(Nhat), main = "Absolute abundance", xlab = "Rdiff", ylab = "Fishing mortality (inst)")

image(1:10, 1:10, t(Bhat), main = "Absolute biomass", xlab = "Rdiff", ylab = "Fishing mortality (inst)")

image(1:10, 1:10, t(SPR), main = "TEP", xlab = "Rdiff", ylab = "Fishing mortality (inst)")

image(1:10, 1:10, t(Total_Yield), main = "Yield", xlab = "Rdiff", ylab = "Fishing mortality (inst)")

image(1:10, 1:10, t(Total_Catch), main = "Catch", xlab = "Rdiff", ylab = "Fishing mortality (inst)")

#Calculating and visualizing catch per unit effort

#Annual harvest rate
harvest<-1-exp(-mu_f)
harvestmat<-matrix(nrow = 10, ncol = 10, data = rep(harvest,10))

#CPUE with actual catch numbers
Total_Catch2 = Total_Catch[-1,]
cpue_catch=Total_Catch2/harvestmat
Total_Catch2 = Total_Catch[-1,]
cpue_catch=Total_Catch2/harvestmat
image(1:10, 1:10, t(cpue_catch), main = "CPUE", xlab = "Rdiff", ylab = "Fishing mortality (inst)", col=hcl.colors(12,"Mako", rev = TRUE))

#CPUE with actual catch mass
Total_Yield2<-Total_Yield[-1,]
cpue_yield=Total_Yield2/harvestmat
image(1:10, 1:10, t(cpue_yield), main = "CPUE", xlab = "Rdiff", ylab = "Fishing mortality (inst)", col=hcl.colors(12,"Mako", rev = TRUE))
